kind: Cluster
metadata:
  name: cluster01
spec:
  hosts:
  - {name: kubesphere, address: 10.20.20.10, internalAddress: 10.20.20.10, privateKeyPath: "~/.ssh/id_ed25519"}
  roleGroups:
    etcd:
    - kubesphere
    master:
    - kubesphere
    worker:
    - kubesphere
  controlPlaneEndpoint:
    internalLoadbalancer: haproxy
  system:
    timezone: "Asia/Shanghai"
    postInstall:
      - name: clean tmps files
        bash: |
          rm -fr /tmp/kubekey/*
    #skipConfigureOS: true
  kubernetes:
    containerManager: containerd
    kata:
      enabled: true
    nodeFeatureDiscovery:
      enabled: true
  network:
    multusCNI:
      enabled: true
