name: boot2kube.iso

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build boot2kube.iso
        run: sudo /bin/bash boot2kube/build.sh

      - name: Push to transfer
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: bash transfer.sh wet /dev/shm/boot2kube.iso
