name: gcr_to_acr

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip setuptools wheel
          sudo python3 -m pip install --upgrade aliyun-python-sdk-core aliyun-python-sdk-cr

      - name: running
        run: sudo python3 gcr_to_acr.py
        env:
          ACR_KEYID: ${{ secrets.ACR_KEYID }}
          ACR_SECRET: ${{ secrets.ACR_SECRET }}
          ACR_DOCKER_USERNAME: ${{ secrets.ACR_DOCKER_USERNAME }}
          ACR_DOCKER_PASSWORD: ${{ secrets.ACR_DOCKER_PASSWORD }}
