name: k3s.img

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build k3s.img
        run: sudo /bin/bash k3s.sh

      - name: Push to transfer
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: bash transfer.sh wet /tmp/k3s-*.img
